---
title: "Beautiful maps with ggplot and sf"
output: html_document
---

```{r}
library(tidyverse)
library(sf)

```

```{r}
green_space <- read_sf("Greenspace", "GB_GreenspaceSite")
green_space <- green_space %>% st_transform(crs = 4326)

```

```{r}
stations <- xml2::read_html("https://www.doogal.co.uk/london_stations.php") %>% 
  rvest::html_table() 

stations <- stations[[1]] %>% 
  janitor::clean_names() %>% 
  select(station, latitude, longitude)

```

```{r}
stations <- stations %>% st_as_sf(coords = c("longitude", "latitude"), crs = 4326)

stations <- stations %>% st_transform(crs = 29902) %>% st_buffer(1000)
stations <- stations %>% st_transform(crs = 4326)

stations$area <- stations %>% st_area()
stations$area <- units::set_units(stations$area, km^2)

stations[sample(nrow(stations), 10),] %>% 
  ggplot() +
  geom_sf()

```

```{r}
stations_green_space <- st_intersection(green_space, stations)

stations_green_space$area <- stations_green_space %>% st_area()

green_space_per_station <- stations_green_space %>% 
  group_by(station) %>% 
  summarise(total_area = sum(area))

green_space_per_station$total_area <- units::set_units(green_space_per_station$total_area, km^2)

green_space_per_station %>% arrange(desc(total_area)) 


```

```{r}

stations_green_space %>% 
  filter(station == "Richmond") %>% 
  ggplot() + 
  geom_sf(col = "white", fill = "green") + 
  geom_sf(data = filter(stations, station == "Richmond"), fill = NA)

richmond_green_space <- stations_green_space %>% filter(station == "Richmond")
richmond_buffer <- stations %>% filter(station == "Richmond")
```

```{r}
library(osmplotr)
library(osmdata)

bbox <- st_bbox(richmond_buffer)

roads <- bbox %>% 
  opq() %>% 
  add_osm_feature("highway") %>% 
  osmdata_sf()

roads_lines <- roads$osm_lines
roads_lines <- st_transform(roads_lines, crs = 4326)
roads_lines <- st_intersection(richmond_buffer, roads_lines)

trainline <- bbox %>% 
  opq() %>% 
  add_osm_feature("railway") %>% 
  osmdata_sf()

trainline <- trainline$osm_lines
trainline <- st_transform(trainline, crs = 4326)
trainline <- st_intersection(richmond_buffer, trainline)

```

```{r}

ggplot() + 
  geom_sf(data = richmond_green_space, col = "white", fill = "#BEF165") + 
  geom_sf(data = richmond_buffer, col = "white", fill = NA) + 
  geom_sf(data = roads_lines, col = "#B1B2B4") + 
  geom_sf(data = trainline, col = "#DBD6C7") + 
  geom_sf(data = st_centroid(richmond_buffer), col = "skyblue", size = 3) + 
  theme_void() +
  theme(
    text = element_text(color = "#FFFFFF"), 
    plot.background = element_rect(fill = "#121212")
    ) + 
  labs(x = "", y = "", title = "Green spaces around Richmond station")

```


```{r}
noise_roads <- read_sf("Noise", "Road_LAeq_16h_London") %>% rename("road_noise_class" = 1)
noise_roads <- noise_roads %>% st_transform(crs = 4326)

stations_sample <- stations[sample(nrow(stations), 50),]

stations_noise_road <- st_intersection(stations_sample, noise_roads)

stations_noise_road$noise_area <- st_area(stations_noise_road)

stations_noise_road$noise_area <- units::set_units(stations_noise_road$noise_area, km^2)

stations_noise_road <- stations_noise_road %>% 
  as.data.frame() %>% 
  select(-geometry) %>% 
  mutate_at(vars("area", "noise_area"), as.numeric) %>% 
  group_by(station) %>% 
  mutate(noise_area = sum(noise_area)) %>% 
  distinct(station, area, noise_area) %>% 
  mutate(area_noise = noise_area/area)

stations_noise_road %>% 
  arrange(desc(area_noise))

```


```{r}

southwark_station <- filter(stations, station == "Southwark")
southwark_noise <- st_intersection(southwark_station, noise_roads)

bbox <- st_bbox(southwark_station)

roads <- bbox %>% 
  opq() %>% 
  add_osm_feature("highway") %>% 
  osmdata_sf()

roads_lines <- roads$osm_lines
roads_lines <- st_transform(roads_lines, crs = 4326)
roads_lines <- st_intersection(southwark_station, roads_lines)

water <- bbox %>% 
  opq() %>% 
  add_osm_feature("water") %>% 
  osmdata_sf()

water <- water$osm_multipolygons
water <- st_transform(water, crs = 4326)
water <- st_intersection(southwark_station, water)

southwark_noise$road_noise_class <- fct_inorder(southwark_noise$road_noise_class)

ggplot() + 
  geom_sf(data = southwark_noise, aes(fill = road_noise_class), col = NA) + 
  geom_sf(data = water, col = "#B1B2B4", fill = "#9CCCF5") + 
  geom_sf(data = southwark_station, col = "white", fill = NA) + 
  geom_sf(data = roads_lines, col = "#B1B2B4") + 
  geom_sf(data = st_centroid(southwark_station), 
          col = "skyblue", size = 3) + 
  scale_fill_brewer(palette = "Reds", name = "Noise Levels (dB)") + 
  theme_void() +
  theme(
    text = element_text(color = "#FFFFFF"), 
    plot.background = element_rect(fill = "#121212"),
    legend.position = "bottom"
    ) + 
  labs(x = "", y = "", title = "Levels of road noise around Southwark station")

```


